version: '3'

services:
  myDB:
    image: postgres:15.3
    container_name: scrapping-challenge-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=scrapping-challenge
    volumes:
      - ./postgres:/var/lib/postgresql/data